<?php
/**
 * REST endpoints for artist-driven artwork/event removal.
 *
 * Single endpoint:
 *   POST /agnosis/v1/removal/{id}/confirm?token=
 *
 * The artist clicks a signed link from the removal notification email.
 * This endpoint validates the token, trashes the post — and, when Lingua
 * Forge is active, every translation linked into its TRID group along with
 * it, via linguaforge_trash_translation_group() (LF 2.5.4+) — and fires
 * 'agnosis_post_removed' — no admin involvement required. Covers both
 * agnosis_artwork and agnosis_event (see REMOVABLE_TYPES; widened
 * 2026-07-06 — remove@ used to be artwork-only).
 *
 * Without the cascade, only the primary-language post was ever trashed: an
 * artist's removal request left every translated copy live and publicly
 * visible, with no admin-facing signal that anything was left behind. Falls
 * back to a plain wp_trash_post() of just the primary post when Lingua
 * Forge isn't active — there is no translation group to cascade to.
 *
 * Token lifecycle (mirrors ReviewEndpoints):
 *   • Generated by PostCreator::handle_removal_request() on incoming remove@ email.
 *   • Stored in _agnosis_removal_token / _agnosis_removal_expiry post meta.
 *   • Single-use: token meta is deleted after a successful confirm.
 *   • Expires after 7 days.
 *
 * @package Agnosis\Publishing
 */

declare(strict_types=1);

namespace Agnosis\Publishing;

class RemovalEndpoints {

	/** REST namespace shared across Agnosis endpoints. */
	private const NS = 'agnosis/v1';

	/**
	 * Post types artists can request removal of via remove@ (2026-07-06:
	 * widened from artwork-only to also cover events — PostCreator's
	 * handle_removal_request() now searches both).
	 */
	private const REMOVABLE_TYPES = [ 'agnosis_artwork', 'agnosis_event' ];

	// -------------------------------------------------------------------------
	// Registration
	// -------------------------------------------------------------------------

	/** Register REST routes on 'rest_api_init'. */
	public function register_routes(): void {
		register_rest_route(
			self::NS,
			'/removal/(?P<id>\d+)/confirm',
			[
				'methods'             => \WP_REST_Server::CREATABLE, // POST
				'callback'            => [ $this, 'confirm' ],
				'permission_callback' => [ $this, 'check_permission' ],
				'args'                => [
					'id'    => [
						'required'          => true,
						'validate_callback' => fn( $v ) => is_numeric( $v ) && (int) $v > 0,
						'sanitize_callback' => 'absint',
					],
					'token' => [
						'required'          => true,
						'validate_callback' => fn( $v ) => is_string( $v ) && strlen( $v ) > 0,
						'sanitize_callback' => 'sanitize_text_field',
					],
				],
			]
		);
	}

	// -------------------------------------------------------------------------
	// Endpoint handlers
	// -------------------------------------------------------------------------

	/**
	 * POST /agnosis/v1/removal/{id}/confirm?token=
	 *
	 * Validates the signed removal token and, if valid, trashes the post
	 * (artwork or event — see REMOVABLE_TYPES) and every translation linked
	 * into its TRID group (see trash_post_and_translations()).
	 *
	 * @param \WP_REST_Request $request Incoming REST request.
	 * @return \WP_REST_Response|\WP_Error
	 */
	public function confirm( \WP_REST_Request $request ): \WP_REST_Response|\WP_Error {
		$post_id       = (int) $request->get_param( 'id' );
		$supplied_token = (string) $request->get_param( 'token' );

		$post = get_post( $post_id );
		if ( ! $post || ! in_array( $post->post_type, self::REMOVABLE_TYPES, true ) ) {
			return new \WP_Error(
				'agnosis_removal_not_found',
				__( 'Artwork or event not found.', 'agnosis' ),
				[ 'status' => 404 ]
			);
		}

		$label = $this->type_label( $post->post_type );

		// Already trashed — idempotent success.
		if ( 'trash' === $post->post_status ) {
			return rest_ensure_response( [
				'removed' => true,
				/* translators: %s: "artwork" or "event" */
				'message' => sprintf( __( '%s already removed.', 'agnosis' ), ucfirst( $label ) ),
			] );
		}

		$error = self::verify_token( $post_id, $supplied_token );
		if ( is_wp_error( $error ) ) {
			return $error;
		}

		// Consume the token before acting (prevents replay).
		delete_post_meta( $post_id, '_agnosis_removal_token' );
		delete_post_meta( $post_id, '_agnosis_removal_expiry' );

		$artist_id = (int) $post->post_author;

		if ( ! $this->trash_post_and_translations( $post_id ) ) {
			return new \WP_Error(
				'agnosis_removal_failed',
				/* translators: %s: "artwork" or "event" */
				sprintf( __( 'Could not remove the %s. Please try again.', 'agnosis' ), $label ),
				[ 'status' => 500 ]
			);
		}

		/**
		 * Fires after an artwork or event has been trashed by artist request.
		 *
		 * @param int $post_id   The trashed post ID.
		 * @param int $artist_id The artist's WordPress user ID.
		 */
		do_action( 'agnosis_post_removed', $post_id, $artist_id );

		return rest_ensure_response( [
			'removed' => true,
			/* translators: %s: "artwork" or "event" */
			'message' => sprintf( __( 'Your %s has been removed.', 'agnosis' ), $label ),
		] );
	}

	/** Human-readable noun for a removable post type, for use in messages. */
	private function type_label( string $post_type ): string {
		return match ( $post_type ) {
			'agnosis_event' => __( 'event', 'agnosis' ),
			default         => __( 'artwork', 'agnosis' ),
		};
	}

	/**
	 * Trash $post_id and, when Lingua Forge is active, every translation
	 * linked into its TRID group — via linguaforge_trash_translation_group()
	 * (LF 2.5.4+), the same cascade the wp-admin row/bulk "Trash" actions use.
	 *
	 * $check_caps is left at its default (false): this is a trusted
	 * programmatic caller — the signed removal token (verify_token(), called
	 * before this) already establishes the artist's authorization, and this
	 * REST request frequently has no logged-in WP session at all for
	 * current_user_can() to check against. Same convention already used by
	 * linguaforge_trigger_translation()/linguaforge_queue_translation()
	 * elsewhere in this integration.
	 *
	 * Falls back to a plain wp_trash_post() of just $post_id when Lingua
	 * Forge isn't active or the hook isn't present (LF pre-2.5.4) — there is
	 * no translation group to cascade to in that case.
	 *
	 * @return bool True if at least the primary post was trashed.
	 */
	private function trash_post_and_translations( int $post_id ): bool {
		if ( ! function_exists( 'linguaforge_trash_translation_group' ) ) {
			return (bool) wp_trash_post( $post_id );
		}

		$result = linguaforge_trash_translation_group( $post_id );
		return $result['trashed'] > 0;
	}

	// -------------------------------------------------------------------------
	// Private helpers
	// -------------------------------------------------------------------------

	/**
	 * REST permission gate — called before the route callback.
	 *
	 * The removal endpoint is token-only (no cookie auth path). Returning
	 * WP_Error here provides a hard outer boundary so the confirm() callback
	 * is unreachable without a token, even if verify_token() has a logic bug.
	 *
	 * Note: 'token' is also declared required in the route args, so WP will
	 * reject missing tokens before this callback fires. This method handles
	 * the case where the arg is present but empty after sanitisation.
	 *
	 * @param \WP_REST_Request $request Incoming request.
	 * @return true|\WP_Error
	 */
	public function check_permission( \WP_REST_Request $request ): bool|\WP_Error {
		if ( ! empty( sanitize_text_field( (string) $request->get_param( 'token' ) ) ) ) {
			return true; // Verified inside confirm() via verify_token().
		}
		return new \WP_Error(
			'agnosis_auth_required',
			__( 'A valid removal token is required.', 'agnosis' ),
			[ 'status' => 401 ]
		);
	}

	/**
	 * Validate a signed removal token against what is stored in post meta.
	 *
	 * Public and static (fifth audit §2e, mirroring ReviewEndpoints::verify_token()
	 * — fourth audit §3a): a pure, read-only check with no dependency on
	 * instance state, so `Publishing\ReviewConfirm` can call the same check
	 * the REST layer performs one step earlier, on the GET confirm page,
	 * instead of only discovering an expired/invalid link after the artist
	 * clicks the button and hits this REST endpoint.
	 *
	 * @param int    $post_id        The artwork or event post ID.
	 * @param string $supplied_token Token from the request query string.
	 * @return true|\WP_Error
	 */
	public static function verify_token( int $post_id, string $supplied_token ): bool|\WP_Error {
		$stored_token = (string) get_post_meta( $post_id, '_agnosis_removal_token', true );
		$expiry       = (int) get_post_meta( $post_id, '_agnosis_removal_expiry', true );

		if ( empty( $stored_token ) ) {
			return new \WP_Error(
				'agnosis_removal_no_token',
				__( 'No pending removal request found for this item.', 'agnosis' ),
				[ 'status' => 400 ]
			);
		}

		if ( time() > $expiry ) {
			// Clean up expired meta.
			delete_post_meta( $post_id, '_agnosis_removal_token' );
			delete_post_meta( $post_id, '_agnosis_removal_expiry' );

			return new \WP_Error(
				'agnosis_removal_token_expired',
				__( 'The removal link has expired. Please send another removal request.', 'agnosis' ),
				[ 'status' => 410 ]
			);
		}

		if ( ! hash_equals( $stored_token, $supplied_token ) ) {
			return new \WP_Error(
				'agnosis_removal_invalid_token',
				__( 'Invalid removal token.', 'agnosis' ),
				[ 'status' => 403 ]
			);
		}

		return true;
	}
}
